name: AI Backend CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'ai/**'
  pull_request:
    branches: [main]
    paths:
      - 'ai/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ai

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: ai/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: pytest

      - name: Build Docker image
        run: docker build -t ai-backend:${{ github.sha }} .